OCAMLMAKEFILE = ../OCamlMakefile
ANNOTATE = yes
SOURCES = bibtex.ml bib.ml bibtex_parser.mly bibtex_lexer.mll bib2db.ml
RESULT = bib2db
PREDS = camlp4o
PACKS = pcre orm.syntax pa_shelve.syntax

-include $(OCAMLMAKEFILE)
